### ISSUE TITLE
After running ./build.sh how do I use the cursor theme?

### ISSUE THREAD

**Issue by adiultra** [keeferrourke/capitaine-cursors#1]
Please help :cry:

**Comment by keeferrourke** [comment]
The cursor theme gets built into 'build/' to just run

    cp -r build/ ~/.icons/capitaine-cursors

**Comment by adiultra** [comment]
Thanx Works, You should add the command in the install instructions.... Thanx :+1:

**Comment by keeferrourke** [comment]
Updated README with installation instructions :smiley: sorry that it was unclear before.
