### ISSUE TITLE
Color picker on a dark background

### ISSUE THREAD

**Issue by Jazqa** [keeferrourke/capitaine-cursors#13]
Color picker is barely visible on a dark background (f.ex. Breeze Dark). A light element should be added to the cursor to keep it visible on both, light and dark, backgrounds.

**Comment by AlynxZhou** [comment]
need this too

**Comment by AlynxZhou** [comment]
Is there any fix? Need this everyday...

**Comment by AlynxZhou** [comment]
I think this was fixed by me in #26

**Comment by keeferrourke** [comment]
Closing this because I don't think this an issue anymore.

**Comment by AlynxZhou** [comment]
Ah, yeah, I am very happy with this cursor every day XD
