### ISSUE TITLE
Create new release that corresponds to r2.1 in www.opendesktop.org

### ISSUE THREAD

**Issue by BurhanDanger** [keeferrourke/capitaine-cursors#15]

**Comment by yejingchen** [comment]
@keeferrourke would you mind creating a r2.1 release right in this github repo as well? For one thing, I don't need to change the upstream source url in the packaging script. And for another, the id part of the opendesktop url (seems like unix timestamp) changes continuously, so it's probably not a good idea to track new releases using that url.

**Comment by keeferrourke** [comment]
I haven't changed much except for project structure since r2, but sure I will make a new release.
