### ISSUE TITLE
Arch AUR installation fails

### ISSUE THREAD

**Issue by jnsdrtlf** [keeferrourke/capitaine-cursors#17]
On arch, the installation using `yaourt` fails because the package `fakeroot` does not come preinstalled on arch. It is part of the `base-devel` group.
### Solution
```bash
sudo pacman -S base-devel
```
or
```bash
sudo pacman -S fakeroot
```

You might want to add this to the `README.md`

**Comment by keeferrourke** [comment]
You should have installed fakeroot and/or base-devel as part of the installation process. I don't see a need to specify this in the README here. See the [installation guide](https://wiki.archlinux.org/index.php/Installation_guide#Install_the_base_packages).

**Comment by jnsdrtlf** [comment]
`base-devel` is not required to be installed. `base` is sufficient for general usage. But I agree, it would be more usefull if `fakeroot` is added as an dependency in the `PKGBUILD`. Who is responsible for that?

**Comment by keeferrourke** [comment]
> Who is responsible for that?

@jnsdrtlf I haven't run arch linux in over 2 years, and the PKGBUILD is maintained by someone else. I have only linked to it in the README for convenience.

... from the README:
>> There is an AUR PKGBUILD maintained by caiye
