### ISSUE TITLE
Create light cursor variant

### ISSUE THREAD

**Issue by keeferrourke** [keeferrourke/capitaine-cursors#2]
Several users on [DeviantArt](http://krourke.deviantart.com/art/Capitaine-cursors-624189658) have requested that a light version of Capitaine cursors be created for Windows.

Steps to make this a thing:
1. A light variant of each SVG in  `src/svg` should be created, this can be done by simply swapping the fill and stroke colours.
2. The build script should be modified to build both light and dark variants of the cursor theme. 
3. I will have to (reluctantly) boot into Windows and manually generate the light variant from 32x32 PNGs using "RealWorld Cursor Editor".

**Comment by ivcore** [comment]
Does the script need to be for Windows? I think I can make a bash script for it. Should be relatively easy, something like:

1. Copy the `src/svg` to `src/svg-light`
2. For all files in`src/svg-light`:
3. Execute a script or function that swaps the fill and stroke colours.

The build script could be modified to pass the optional argument of 'light version', which would change the `src` directory and execute the above stated script, that would save the time of having to build both `src/svg*` directories.

**Comment by keeferrourke** [comment]
@ivcore Windows is a huge pain... only the xcursor/Linux variant is scripted and built automatically. To make Windows cursors you **have** to use some proprietary program with PNG bases, as far as I know. :nauseated_face: 

If you can generate a `src-light/` directory, and modify the build script to generate an xcursor light-variant, it would be very much appreciated :grin:

**Comment by ivcore** [comment]
I'm not sure how it works but if you only have to generate PNGs from the SVGs I think you can make a macro or script to automate the process in Photoshop, dunno if that helps

**Comment by keeferrourke** [comment]
This has finally been done :) Thanks @Efus10n
