### ISSUE TITLE
Using Prebuilt Cursors in ubuntu. Doesn't Look Like the image.

### ISSUE THREAD

**Issue by niteshkumarniranjan** [keeferrourke/capitaine-cursors#20]
![screenshot from 2017-11-27 01-01-26](https://user-images.githubusercontent.com/20199181/33252847-8ac9f64e-d30e-11e7-92cd-78e1567fde2a.png)

**Comment by keeferrourke** [comment]
Honestly I'm not sure what you're talking about. Your screen capture doesn't include a mouse pointer... and I can assure you that the cursors are generated from the sources in the repository.

Closing for now, due to lack of relevance and clarity...

**Comment by niteshkumarniranjan** [comment]
@keeferrourke I am sorry. I tried to build the source but I haven't installed Inkspace so the problem Happens

**Comment by keeferrourke** [comment]
... what was the problem in the first place?
