### ISSUE TITLE
[Request] add backround to cursors

### ISSUE THREAD

**Issue by azzamsa** [keeferrourke/capitaine-cursors#23]
Sometimes in presentation. We do live coding. We need to point some code with mouse. It's hard for long distance audience to catch up with small icon cursor movement.

Can we have something like [this](https://www.gnome-look.org/p/999801/)

I saw we have wayland and x icon in preview. How can we change default cursor to that icons ?

Thanks for this nice icons.

**Comment by keeferrourke** [comment]
I won't add a background colour to these cursors. There are usually accessibility features of an operating system that will make the cursor more visible. If these are insufficient, I'd suggest using the cursor theme you linked to while you are giving presentations.

You can check the default cursor mappings by cloning this repository, and editing the `src/cursorList` file; then just run the build script.
