### ISSUE TITLE
Building Problem

### ISSUE THREAD

**Issue by iamrahatul** [keeferrourke/capitaine-cursors#24]
~/capitaine-cursors# ./build.sh
./progress.svg: 1: ./progress.svg: inkscape: not found
./wait-19.svg: 1: ./wait-19.svg: inkscape: not found
./wait-07.svg: 1: ./wait-07.svg: inkscape: not found
./bottom_side.svg: 1: ./bottom_side.svg: inkscape: not found
./size_fdiag.svg: 1: ./size_fdiag.svg: inkscape: not found
./wait-20.svg: 1: ./wait-20.svg: inkscape: not found
./wait-03.svg: 1: ./wait-03.svg: inkscape: not found
./x-cursor.svg: 1: ./x-cursor.svg: inkscape: not found
./crosshair.svg: 1: ./crosshair.svg: inkscape: not found
./row-resize.svg: 1: ./row-resize.svg: inkscape: not found
./dnd-move.svg: 1: ./dnd-move.svg: inkscape: not found
./openhand.svg: 1: ./openhand.svg: inkscape: not found
./pirate.svg: 1: ./pirate.svg: inkscape: not found
./copy.svg: 1: ./copy.svg: inkscape: not found
./size_bdiag.svg: 1: ./size_bdiag.svg: inkscape: not found
./progress-13.svg: 1: ./progress-13.svg: inkscape: not found
./dnd-no-drop.svg: 1: ./dnd-no-drop.svg: inkscape: not found
./draft.svg: 1: ./draft.svg: inkscape: not found
./col-resize.svg: 1: ./col-resize.svg: inkscape: not found
./bottom_right_corner.svg: 1: ./bottom_right_corner.svg: inkscape: not found
./wait-17.svg: 1: ./wait-17.svg: inkscape: not found
./default.svg: 1: ./default.svg: inkscape: not found
./pointer.svg: 1: ./pointer.svg: inkscape: not found
./progress-14.svg: 1: ./progress-14.svg: inkscape: not found
./alias.svg: 1: ./alias.svg: inkscape: not found
./wait-09.svg: 1: ./wait-09.svg: inkscape: not found
./wait-04.svg: 1: ./wait-04.svg: inkscape: not found
./progress-21.svg: 1: ./progress-21.svg: inkscape: not found
./progress-15.svg: 1: ./progress-15.svg: inkscape: not found
./not-allowed.svg: 1: ./not-allowed.svg: inkscape: not found
./wait-08.svg: 1: ./wait-08.svg: inkscape: not found
./wait-02.svg: 1: ./wait-02.svg: inkscape: not found
./right_side.svg: 1: ./right_side.svg: inkscape: not found
./progress-03.svg: 1: ./progress-03.svg: inkscape: not found
./progress-06.svg: 1: ./progress-06.svg: inkscape: not found
./progress-18.svg: 1: ./progress-18.svg: inkscape: not found
./no-drop.svg: 1: ./no-drop.svg: inkscape: not found
./wait-14.svg: 1: ./wait-14.svg: inkscape: not found
./color-picker.svg: 1: ./color-picker.svg: inkscape: not found
./progress-07.svg: 1: ./progress-07.svg: inkscape: not found
./wait-15.svg: 1: ./wait-15.svg: inkscape: not found
./context-menu.svg: 1: ./context-menu.svg: inkscape: not found
./wait-23.svg: 1: ./wait-23.svg: inkscape: not found
./wait-05.svg: 1: ./wait-05.svg: inkscape: not found
./size_hor.svg: 1: ./size_hor.svg: inkscape: not found
./all-scroll.svg: 1: ./all-scroll.svg: inkscape: not found
./wait-18.svg: 1: ./wait-18.svg: inkscape: not found
./center_ptr.svg: 1: ./center_ptr.svg: inkscape: not found
./zoom-in.svg: 1: ./zoom-in.svg: inkscape: not found
./progress-23.svg: 1: ./progress-23.svg: inkscape: not found
./progress-01.svg: 1: ./progress-01.svg: inkscape: not found
./vertical-text.svg: 1: ./vertical-text.svg: inkscape: not found
./wait-16.svg: 1: ./wait-16.svg: inkscape: not found
./wayland-cursor.svg: 1: ./wayland-cursor.svg: inkscape: not found
./wait.svg: 1: ./wait.svg: inkscape: not found
./size_ver.svg: 1: ./size_ver.svg: inkscape: not found
./progress-16.svg: 1: ./progress-16.svg: inkscape: not found
./help.svg: 1: ./help.svg: inkscape: not found
./right-arrow.svg: 1: ./right-arrow.svg: inkscape: not found
./cell.svg: 1: ./cell.svg: inkscape: not found
./wait-13.svg: 1: ./wait-13.svg: inkscape: not found
./progress-09.svg: 1: ./progress-09.svg: inkscape: not found
./text.svg: 1: ./text.svg: inkscape: not found
./progress-10.svg: 1: ./progress-10.svg: inkscape: not found
./progress-02.svg: 1: ./progress-02.svg: inkscape: not found
./wait-11.svg: 1: ./wait-11.svg: inkscape: not found
./wait-21.svg: 1: ./wait-21.svg: inkscape: not found
./progress-20.svg: 1: ./progress-20.svg: inkscape: not found
./pencil.svg: 1: ./pencil.svg: inkscape: not found
./wait-22.svg: 1: ./wait-22.svg: inkscape: not found
./right_ptr.svg: 1: ./right_ptr.svg: inkscape: not found
./bottom_left_corner.svg: 1: ./bottom_left_corner.svg: inkscape: not found
./fleur.svg: 1: ./fleur.svg: inkscape: not found
./progress-11.svg: 1: ./progress-11.svg: inkscape: not found
./top_side.svg: 1: ./top_side.svg: inkscape: not found
./progress-12.svg: 1: ./progress-12.svg: inkscape: not found
./progress-19.svg: 1: ./progress-19.svg: inkscape: not found
./progress-08.svg: 1: ./progress-08.svg: inkscape: not found
./progress-22.svg: 1: ./progress-22.svg: inkscape: not found
./wait-10.svg: 1: ./wait-10.svg: inkscape: not found
./progress-05.svg: 1: ./progress-05.svg: inkscape: not found
./wait-12.svg: 1: ./wait-12.svg: inkscape: not found
./left_side.svg: 1: ./left_side.svg: inkscape: not found
./progress-04.svg: 1: ./progress-04.svg: inkscape: not found
./down-arrow.svg: 1: ./down-arrow.svg: inkscape: not found
./top_right_corner.svg: 1: ./top_right_corner.svg: inkscape: not found
./up-arrow.svg: 1: ./up-arrow.svg: inkscape: not found
./wait-06.svg: 1: ./wait-06.svg: inkscape: not found
./left-arrow.svg: 1: ./left-arrow.svg: inkscape: not found
./top_left_corner.svg: 1: ./top_left_corner.svg: inkscape: not found
./zoom-out.svg: 1: ./zoom-out.svg: inkscape: not found
./wait-01.svg: 1: ./wait-01.svg: inkscape: not found
./progress-17.svg: 1: ./progress-17.svg: inkscape: not found
./progress.svg: 1: ./progress.svg: inkscape: not found
./wait-19.svg: 1: ./wait-19.svg: inkscape: not found
./wait-07.svg: 1: ./wait-07.svg: inkscape: not found
./bottom_side.svg: 1: ./bottom_side.svg: inkscape: not found
./size_fdiag.svg: 1: ./size_fdiag.svg: inkscape: not found
./wait-20.svg: 1: ./wait-20.svg: inkscape: not found
./wait-03.svg: 1: ./wait-03.svg: inkscape: not found
./x-cursor.svg: 1: ./x-cursor.svg: inkscape: not found
./crosshair.svg: 1: ./crosshair.svg: inkscape: not found
./row-resize.svg: 1: ./row-resize.svg: inkscape: not found
./dnd-move.svg: 1: ./dnd-move.svg: inkscape: not found
./openhand.svg: 1: ./openhand.svg: inkscape: not found
./pirate.svg: 1: ./pirate.svg: inkscape: not found
./copy.svg: 1: ./copy.svg: inkscape: not found
./size_bdiag.svg: 1: ./size_bdiag.svg: inkscape: not found
./progress-13.svg: 1: ./progress-13.svg: inkscape: not found
./dnd-no-drop.svg: 1: ./dnd-no-drop.svg: inkscape: not found
./draft.svg: 1: ./draft.svg: inkscape: not found
./col-resize.svg: 1: ./col-resize.svg: inkscape: not found
./bottom_right_corner.svg: 1: ./bottom_right_corner.svg: inkscape: not found
./wait-17.svg: 1: ./wait-17.svg: inkscape: not found
./default.svg: 1: ./default.svg: inkscape: not found
./pointer.svg: 1: ./pointer.svg: inkscape: not found
./progress-14.svg: 1: ./progress-14.svg: inkscape: not found
./alias.svg: 1: ./alias.svg: inkscape: not found
./wait-09.svg: 1: ./wait-09.svg: inkscape: not found
./wait-04.svg: 1: ./wait-04.svg: inkscape: not found
./progress-21.svg: 1: ./progress-21.svg: inkscape: not found
./progress-15.svg: 1: ./progress-15.svg: inkscape: not found
./not-allowed.svg: 1: ./not-allowed.svg: inkscape: not found
./wait-08.svg: 1: ./wait-08.svg: inkscape: not found
./wait-02.svg: 1: ./wait-02.svg: inkscape: not found
./right_side.svg: 1: ./right_side.svg: inkscape: not found
./progress-03.svg: 1: ./progress-03.svg: inkscape: not found
./progress-06.svg: 1: ./progress-06.svg: inkscape: not found
./progress-18.svg: 1: ./progress-18.svg: inkscape: not found
./no-drop.svg: 1: ./no-drop.svg: inkscape: not found
./wait-14.svg: 1: ./wait-14.svg: inkscape: not found
./color-picker.svg: 1: ./color-picker.svg: inkscape: not found
./progress-07.svg: 1: ./progress-07.svg: inkscape: not found
./wait-15.svg: 1: ./wait-15.svg: inkscape: not found
./context-menu.svg: 1: ./context-menu.svg: inkscape: not found
./wait-23.svg: 1: ./wait-23.svg: inkscape: not found
./wait-05.svg: 1: ./wait-05.svg: inkscape: not found
./size_hor.svg: 1: ./size_hor.svg: inkscape: not found
./all-scroll.svg: 1: ./all-scroll.svg: inkscape: not found
./wait-18.svg: 1: ./wait-18.svg: inkscape: not found
./center_ptr.svg: 1: ./center_ptr.svg: inkscape: not found
./zoom-in.svg: 1: ./zoom-in.svg: inkscape: not found
./progress-23.svg: 1: ./progress-23.svg: inkscape: not found
./progress-01.svg: 1: ./progress-01.svg: inkscape: not found
./vertical-text.svg: 1: ./vertical-text.svg: inkscape: not found
./wait-16.svg: 1: ./wait-16.svg: inkscape: not found
./wayland-cursor.svg: 1: ./wayland-cursor.svg: inkscape: not found
./wait.svg: 1: ./wait.svg: inkscape: not found
./size_ver.svg: 1: ./size_ver.svg: inkscape: not found
./progress-16.svg: 1: ./progress-16.svg: inkscape: not found
./help.svg: 1: ./help.svg: inkscape: not found
./right-arrow.svg: 1: ./right-arrow.svg: inkscape: not found
./cell.svg: 1: ./cell.svg: inkscape: not found
./wait-13.svg: 1: ./wait-13.svg: inkscape: not found
./progress-09.svg: 1: ./progress-09.svg: inkscape: not found
./text.svg: 1: ./text.svg: inkscape: not found
./progress-10.svg: 1: ./progress-10.svg: inkscape: not found
./progress-02.svg: 1: ./progress-02.svg: inkscape: not found
./wait-11.svg: 1: ./wait-11.svg: inkscape: not found
./wait-21.svg: 1: ./wait-21.svg: inkscape: not found
./progress-20.svg: 1: ./progress-20.svg: inkscape: not found
./pencil.svg: 1: ./pencil.svg: inkscape: not found
./wait-22.svg: 1: ./wait-22.svg: inkscape: not found
./right_ptr.svg: 1: ./right_ptr.svg: inkscape: not found
./bottom_left_corner.svg: 1: ./bottom_left_corner.svg: inkscape: not found
./fleur.svg: 1: ./fleur.svg: inkscape: not found
./progress-11.svg: 1: ./progress-11.svg: inkscape: not found
./top_side.svg: 1: ./top_side.svg: inkscape: not found
./progress-12.svg: 1: ./progress-12.svg: inkscape: not found
./progress-19.svg: 1: ./progress-19.svg: inkscape: not found
./progress-08.svg: 1: ./progress-08.svg: inkscape: not found
./progress-22.svg: 1: ./progress-22.svg: inkscape: not found
./wait-10.svg: 1: ./wait-10.svg: inkscape: not found
./progress-05.svg: 1: ./progress-05.svg: inkscape: not found
./wait-12.svg: 1: ./wait-12.svg: inkscape: not found
./left_side.svg: 1: ./left_side.svg: inkscape: not found
./progress-04.svg: 1: ./progress-04.svg: inkscape: not found
./down-arrow.svg: 1: ./down-arrow.svg: inkscape: not found
./top_right_corner.svg: 1: ./top_right_corner.svg: inkscape: not found
./up-arrow.svg: 1: ./up-arrow.svg: inkscape: not found
./wait-06.svg: 1: ./wait-06.svg: inkscape: not found
./left-arrow.svg: 1: ./left-arrow.svg: inkscape: not found
./top_left_corner.svg: 1: ./top_left_corner.svg: inkscape: not found
./zoom-out.svg: 1: ./zoom-out.svg: inkscape: not found
./wait-01.svg: 1: ./wait-01.svg: inkscape: not found
./progress-17.svg: 1: ./progress-17.svg: inkscape: not found
./progress.svg: 1: ./progress.svg: inkscape: not found
./wait-19.svg: 1: ./wait-19.svg: inkscape: not found
./wait-07.svg: 1: ./wait-07.svg: inkscape: not found
./bottom_side.svg: 1: ./bottom_side.svg: inkscape: not found
./size_fdiag.svg: 1: ./size_fdiag.svg: inkscape: not found
./wait-20.svg: 1: ./wait-20.svg: inkscape: not found
./wait-03.svg: 1: ./wait-03.svg: inkscape: not found
./x-cursor.svg: 1: ./x-cursor.svg: inkscape: not found
./crosshair.svg: 1: ./crosshair.svg: inkscape: not found
./row-resize.svg: 1: ./row-resize.svg: inkscape: not found
./dnd-move.svg: 1: ./dnd-move.svg: inkscape: not found
./openhand.svg: 1: ./openhand.svg: inkscape: not found
./pirate.svg: 1: ./pirate.svg: inkscape: not found
./copy.svg: 1: ./copy.svg: inkscape: not found
./size_bdiag.svg: 1: ./size_bdiag.svg: inkscape: not found
./progress-13.svg: 1: ./progress-13.svg: inkscape: not found
./dnd-no-drop.svg: 1: ./dnd-no-drop.svg: inkscape: not found
./draft.svg: 1: ./draft.svg: inkscape: not found
./col-resize.svg: 1: ./col-resize.svg: inkscape: not found
./bottom_right_corner.svg: 1: ./bottom_right_corner.svg: inkscape: not found
./wait-17.svg: 1: ./wait-17.svg: inkscape: not found
./default.svg: 1: ./default.svg: inkscape: not found
./pointer.svg: 1: ./pointer.svg: inkscape: not found
./progress-14.svg: 1: ./progress-14.svg: inkscape: not found
./alias.svg: 1: ./alias.svg: inkscape: not found
./wait-09.svg: 1: ./wait-09.svg: inkscape: not found
./wait-04.svg: 1: ./wait-04.svg: inkscape: not found
./progress-21.svg: 1: ./progress-21.svg: inkscape: not found
./progress-15.svg: 1: ./progress-15.svg: inkscape: not found
./not-allowed.svg: 1: ./not-allowed.svg: inkscape: not found
./wait-08.svg: 1: ./wait-08.svg: inkscape: not found
./wait-02.svg: 1: ./wait-02.svg: inkscape: not found
./right_side.svg: 1: ./right_side.svg: inkscape: not found
./progress-03.svg: 1: ./progress-03.svg: inkscape: not found
./progress-06.svg: 1: ./progress-06.svg: inkscape: not found
./progress-18.svg: 1: ./progress-18.svg: inkscape: not found
./no-drop.svg: 1: ./no-drop.svg: inkscape: not found
./wait-14.svg: 1: ./wait-14.svg: inkscape: not found
./color-picker.svg: 1: ./color-picker.svg: inkscape: not found
./progress-07.svg: 1: ./progress-07.svg: inkscape: not found
./wait-15.svg: 1: ./wait-15.svg: inkscape: not found
./context-menu.svg: 1: ./context-menu.svg: inkscape: not found
./wait-23.svg: 1: ./wait-23.svg: inkscape: not found
./wait-05.svg: 1: ./wait-05.svg: inkscape: not found
./size_hor.svg: 1: ./size_hor.svg: inkscape: not found
./all-scroll.svg: 1: ./all-scroll.svg: inkscape: not found
./wait-18.svg: 1: ./wait-18.svg: inkscape: not found
./center_ptr.svg: 1: ./center_ptr.svg: inkscape: not found
./zoom-in.svg: 1: ./zoom-in.svg: inkscape: not found
./progress-23.svg: 1: ./progress-23.svg: inkscape: not found
./progress-01.svg: 1: ./progress-01.svg: inkscape: not found
./vertical-text.svg: 1: ./vertical-text.svg: inkscape: not found
./wait-16.svg: 1: ./wait-16.svg: inkscape: not found
./wayland-cursor.svg: 1: ./wayland-cursor.svg: inkscape: not found
./wait.svg: 1: ./wait.svg: inkscape: not found
./size_ver.svg: 1: ./size_ver.svg: inkscape: not found
./progress-16.svg: 1: ./progress-16.svg: inkscape: not found
./help.svg: 1: ./help.svg: inkscape: not found
./right-arrow.svg: 1: ./right-arrow.svg: inkscape: not found
./cell.svg: 1: ./cell.svg: inkscape: not found
./wait-13.svg: 1: ./wait-13.svg: inkscape: not found
./progress-09.svg: 1: ./progress-09.svg: inkscape: not found
./text.svg: 1: ./text.svg: inkscape: not found
./progress-10.svg: 1: ./progress-10.svg: inkscape: not found
./progress-02.svg: 1: ./progress-02.svg: inkscape: not found
./wait-11.svg: 1: ./wait-11.svg: inkscape: not found
./wait-21.svg: 1: ./wait-21.svg: inkscape: not found
./progress-20.svg: 1: ./progress-20.svg: inkscape: not found
./pencil.svg: 1: ./pencil.svg: inkscape: not found
./wait-22.svg: 1: ./wait-22.svg: inkscape: not found
./right_ptr.svg: 1: ./right_ptr.svg: inkscape: not found
./bottom_left_corner.svg: 1: ./bottom_left_corner.svg: inkscape: not found
./fleur.svg: 1: ./fleur.svg: inkscape: not found
./progress-11.svg: 1: ./progress-11.svg: inkscape: not found
./top_side.svg: 1: ./top_side.svg: inkscape: not found
./progress-12.svg: 1: ./progress-12.svg: inkscape: not found
./progress-19.svg: 1: ./progress-19.svg: inkscape: not found
./progress-08.svg: 1: ./progress-08.svg: inkscape: not found
./progress-22.svg: 1: ./progress-22.svg: inkscape: not found
./wait-10.svg: 1: ./wait-10.svg: inkscape: not found
./progress-05.svg: 1: ./progress-05.svg: inkscape: not found
./wait-12.svg: 1: ./wait-12.svg: inkscape: not found
./left_side.svg: 1: ./left_side.svg: inkscape: not found
./progress-04.svg: 1: ./progress-04.svg: inkscape: not found
./down-arrow.svg: 1: ./down-arrow.svg: inkscape: not found
./top_right_corner.svg: 1: ./top_right_corner.svg: inkscape: not found
./up-arrow.svg: 1: ./up-arrow.svg: inkscape: not found
./wait-06.svg: 1: ./wait-06.svg: inkscape: not found
./left-arrow.svg: 1: ./left-arrow.svg: inkscape: not found
./top_left_corner.svg: 1: ./top_left_corner.svg: inkscape: not found
./zoom-out.svg: 1: ./zoom-out.svg: inkscape: not found
./wait-01.svg: 1: ./wait-01.svg: inkscape: not found
./progress-17.svg: 1: ./progress-17.svg: inkscape: not found
./progress.svg: 1: ./progress.svg: inkscape: not found
./wait-19.svg: 1: ./wait-19.svg: inkscape: not found
./wait-07.svg: 1: ./wait-07.svg: inkscape: not found
./bottom_side.svg: 1: ./bottom_side.svg: inkscape: not found
./size_fdiag.svg: 1: ./size_fdiag.svg: inkscape: not found
./wait-20.svg: 1: ./wait-20.svg: inkscape: not found
./wait-03.svg: 1: ./wait-03.svg: inkscape: not found
./x-cursor.svg: 1: ./x-cursor.svg: inkscape: not found
./crosshair.svg: 1: ./crosshair.svg: inkscape: not found
./row-resize.svg: 1: ./row-resize.svg: inkscape: not found
./dnd-move.svg: 1: ./dnd-move.svg: inkscape: not found
./openhand.svg: 1: ./openhand.svg: inkscape: not found
./pirate.svg: 1: ./pirate.svg: inkscape: not found
./copy.svg: 1: ./copy.svg: inkscape: not found
./size_bdiag.svg: 1: ./size_bdiag.svg: inkscape: not found
./progress-13.svg: 1: ./progress-13.svg: inkscape: not found
./dnd-no-drop.svg: 1: ./dnd-no-drop.svg: inkscape: not found
./draft.svg: 1: ./draft.svg: inkscape: not found
./col-resize.svg: 1: ./col-resize.svg: inkscape: not found
./bottom_right_corner.svg: 1: ./bottom_right_corner.svg: inkscape: not found
./wait-17.svg: 1: ./wait-17.svg: inkscape: not found
./default.svg: 1: ./default.svg: inkscape: not found
./pointer.svg: 1: ./pointer.svg: inkscape: not found
./progress-14.svg: 1: ./progress-14.svg: inkscape: not found
./alias.svg: 1: ./alias.svg: inkscape: not found
./wait-09.svg: 1: ./wait-09.svg: inkscape: not found
./wait-04.svg: 1: ./wait-04.svg: inkscape: not found
./progress-21.svg: 1: ./progress-21.svg: inkscape: not found
./progress-15.svg: 1: ./progress-15.svg: inkscape: not found
./not-allowed.svg: 1: ./not-allowed.svg: inkscape: not found
./wait-08.svg: 1: ./wait-08.svg: inkscape: not found
./wait-02.svg: 1: ./wait-02.svg: inkscape: not found
./right_side.svg: 1: ./right_side.svg: inkscape: not found
./progress-03.svg: 1: ./progress-03.svg: inkscape: not found
./progress-06.svg: 1: ./progress-06.svg: inkscape: not found
./progress-18.svg: 1: ./progress-18.svg: inkscape: not found
./no-drop.svg: 1: ./no-drop.svg: inkscape: not found
./wait-14.svg: 1: ./wait-14.svg: inkscape: not found
./color-picker.svg: 1: ./color-picker.svg: inkscape: not found
./progress-07.svg: 1: ./progress-07.svg: inkscape: not found
./wait-15.svg: 1: ./wait-15.svg: inkscape: not found
./context-menu.svg: 1: ./context-menu.svg: inkscape: not found
./wait-23.svg: 1: ./wait-23.svg: inkscape: not found
./wait-05.svg: 1: ./wait-05.svg: inkscape: not found
./size_hor.svg: 1: ./size_hor.svg: inkscape: not found
./all-scroll.svg: 1: ./all-scroll.svg: inkscape: not found
./wait-18.svg: 1: ./wait-18.svg: inkscape: not found
./center_ptr.svg: 1: ./center_ptr.svg: inkscape: not found
./zoom-in.svg: 1: ./zoom-in.svg: inkscape: not found
./progress-23.svg: 1: ./progress-23.svg: inkscape: not found
./progress-01.svg: 1: ./progress-01.svg: inkscape: not found
./vertical-text.svg: 1: ./vertical-text.svg: inkscape: not found
./wait-16.svg: 1: ./wait-16.svg: inkscape: not found
./wayland-cursor.svg: 1: ./wayland-cursor.svg: inkscape: not found
./wait.svg: 1: ./wait.svg: inkscape: not found
./size_ver.svg: 1: ./size_ver.svg: inkscape: not found
./progress-16.svg: 1: ./progress-16.svg: inkscape: not found
./help.svg: 1: ./help.svg: inkscape: not found
./right-arrow.svg: 1: ./right-arrow.svg: inkscape: not found
./cell.svg: 1: ./cell.svg: inkscape: not found
./wait-13.svg: 1: ./wait-13.svg: inkscape: not found
./progress-09.svg: 1: ./progress-09.svg: inkscape: not found
./text.svg: 1: ./text.svg: inkscape: not found
./progress-10.svg: 1: ./progress-10.svg: inkscape: not found
./progress-02.svg: 1: ./progress-02.svg: inkscape: not found
./wait-11.svg: 1: ./wait-11.svg: inkscape: not found
./wait-21.svg: 1: ./wait-21.svg: inkscape: not found
./progress-20.svg: 1: ./progress-20.svg: inkscape: not found
./pencil.svg: 1: ./pencil.svg: inkscape: not found
./wait-22.svg: 1: ./wait-22.svg: inkscape: not found
./right_ptr.svg: 1: ./right_ptr.svg: inkscape: not found
./bottom_left_corner.svg: 1: ./bottom_left_corner.svg: inkscape: not found
./fleur.svg: 1: ./fleur.svg: inkscape: not found
./progress-11.svg: 1: ./progress-11.svg: inkscape: not found
./top_side.svg: 1: ./top_side.svg: inkscape: not found
./progress-12.svg: 1: ./progress-12.svg: inkscape: not found
./progress-19.svg: 1: ./progress-19.svg: inkscape: not found
./progress-08.svg: 1: ./progress-08.svg: inkscape: not found
./progress-22.svg: 1: ./progress-22.svg: inkscape: not found
./wait-10.svg: 1: ./wait-10.svg: inkscape: not found
./progress-05.svg: 1: ./progress-05.svg: inkscape: not found
./wait-12.svg: 1: ./wait-12.svg: inkscape: not found
./left_side.svg: 1: ./left_side.svg: inkscape: not found
./progress-04.svg: 1: ./progress-04.svg: inkscape: not found
./down-arrow.svg: 1: ./down-arrow.svg: inkscape: not found
./top_right_corner.svg: 1: ./top_right_corner.svg: inkscape: not found
./up-arrow.svg: 1: ./up-arrow.svg: inkscape: not found
./wait-06.svg: 1: ./wait-06.svg: inkscape: not found
./left-arrow.svg: 1: ./left-arrow.svg: inkscape: not found
./top_left_corner.svg: 1: ./top_left_corner.svg: inkscape: not found
./zoom-out.svg: 1: ./zoom-out.svg: inkscape: not found
./wait-01.svg: 1: ./wait-01.svg: inkscape: not found
./progress-17.svg: 1: ./progress-17.svg: inkscape: not found
PNG error while reading x1/alias.png!
PNG error while reading x1/all-scroll.png!
PNG error while reading x1/bottom_left_corner.png!
PNG error while reading x1/bottom_right_corner.png!
PNG error while reading x1/bottom_side.png!
PNG error while reading x1/cell.png!
PNG error while reading x1/center_ptr.png!
PNG error while reading x1/color-picker.png!
PNG error while reading x1/col-resize.png!
PNG error while reading x1/context-menu.png!
PNG error while reading x1/copy.png!
PNG error while reading x1/crosshair.png!
PNG error while reading x1/default.png!
PNG error while reading x1/dnd-move.png!
PNG error while reading x1/dnd-no-drop.png!
PNG error while reading x1/down-arrow.png!
PNG error while reading x1/draft.png!
PNG error while reading x1/fleur.png!
PNG error while reading x1/help.png!
PNG error while reading x1/left-arrow.png!
PNG error while reading x1/left_side.png!
PNG error while reading x1/no-drop.png!
PNG error while reading x1/not-allowed.png!
PNG error while reading x1/openhand.png!
PNG error while reading x1/pencil.png!
PNG error while reading x1/pirate.png!
PNG error while reading x1/pointer.png!
PNG error while reading x1/progress-01.png!
PNG error while reading x1/right-arrow.png!
PNG error while reading x1/right_ptr.png!
PNG error while reading x1/right_side.png!
PNG error while reading x1/row-resize.png!
PNG error while reading x1/size_bdiag.png!
PNG error while reading x1/size_fdiag.png!
PNG error while reading x1/size_hor.png!
PNG error while reading x1/size_ver.png!
PNG error while reading x1/text.png!
PNG error while reading x1/top_left_corner.png!
PNG error while reading x1/top_right_corner.png!
PNG error while reading x1/top_side.png!
PNG error while reading x1/up-arrow.png!
PNG error while reading x1/vertical-text.png!
PNG error while reading x1/wait-01.png!
PNG error while reading x1/wayland-cursor.png!
PNG error while reading x1/x-cursor.png!
PNG error while reading x1/zoom-in.png!
PNG error while reading x1/zoom-out.png!
Generating cursor theme... DONE
Generating shortcuts... DONE
Generating Theme Index... DONE

**Comment by keeferrourke** [comment]
Install inkscape.
