### ISSUE TITLE
Window corner cursors are broken

### ISSUE THREAD

**Issue by mleko69** [keeferrourke/capitaine-cursors#27]
Hi, first of all THX for this cursor theme! :)
Hovering on window corners doesn't show a proper cursor (at least on KDE Plasma): 
![screenshot_20190202_114235](https://user-images.githubusercontent.com/22177132/52163292-4e516e00-26e0-11e9-842a-2faf8fd51c8b.png)

A small hack, that is adding the line `Inherits=breeze_cursors` to the index.theme _fixes_ the issue by using a Breeze variant of missing/broken cursor.

![screenshot_20190202_114411](https://user-images.githubusercontent.com/22177132/52163335-cd46a680-26e0-11e9-968f-9d8058cdc379.png)

**Comment by mleko69** [comment]
After messing around I've found that some symlinks are missing. Copying them from original Breeze fixed the issue. Now Plasma shows all cursors properly:
[capitaine-cursors-with-missing-symlinks.tar.gz](https://github.com/keeferrourke/capitaine-cursors/files/2824357/capitaine-cursors-with-missing-symlinks.tar.gz)

**Comment by al2me6** [comment]
Still occurring on r3 in Arch Linux. Any chance of a fix?

**Comment by keeferrourke** [comment]
I haven't gotten around to fixing this yet, sorry.

**Comment by mleko69** [comment]
The fix is literally in the tarball I uploaded...
![Screenshot_20190730_221744](https://user-images.githubusercontent.com/22177132/62162296-788a8e00-b307-11e9-9023-a811e3f7dad7.png)

**Comment by al2me6** [comment]
@mleko69 Keep in mind that the symlinks need to be incorporated into the build process.

**Comment by hexchain** [comment]
The corresponding icons should be `{bottom,top}_{left,right}_corner`, which are already in the theme. The actual problem could be these `{n,s}{e,w}-resize` symlinks:

```
lrwxrwxrwx 1 root root      16 Nov  8 12:49 ne-resize -> top_right_corner
lrwxrwxrwx 1 root root      15 Nov  8 12:49 nw-resize -> top_left_corner
lrwxrwxrwx 1 root root      19 Nov  8 12:49 se-resize -> bottom_right_corner
lrwxrwxrwx 1 root root      18 Nov  8 12:49 sw-resize -> bottom_left_corner
```

After manually adding them I no longer see Adwaita icons there, on Plasma 5.18.
