### ISSUE TITLE
HDPI support ?

### ISSUE THREAD

**Issue by yao89** [keeferrourke/capitaine-cursors#28]
Hi, super great job for the macOS lovers who have to play with windaube times to times..

Unfortunaltly, there seems to not have HDPI versions of icons (like Retina) ?
I'm on a 28" 4K screen (150%), and the icons are a little blurry.

Thanks in advance ;)

**Comment by keeferrourke** [comment]
Hmm, I don't have a 4K display to play with. Would you mind specifying what the correct icon size would be? (I won't be able to address this any time soon, but maybe if I discover a hole in my schedule I can try to take a look)

**Comment by yao89** [comment]
Hi, correct icon size = icon size for 1080p * 2, simply ;)
But I think you have to name the icon files differently. For macOS, on retina screen you have to name it "something@2x.png".

Thanks in advance

**Comment by i2mo** [comment]
Is this what you want?
https://github.com/DebauchedSloth/capitaine-cursors/raw/e3cf81f88cbfac357b059f32b83eaa9ba29558cf/capitaine-cursors-hidpi-src.tar.gz

Found here: https://aur.archlinux.org/packages/capitaine-cursors-hidpi

**Comment by keeferrourke** [comment]
Looks like it :) HiDPI size appears to be ~80px from reading that fork.

**Comment by insign** [comment]
I used hidpi in ArchLinux, last year, it is on AUR repo as mentioned above.

**Comment by keeferrourke** [comment]
Working on this now. Refactoring the build process to make it trivial to support higher DPIs with a bit of easy math.

Gonna be a big change -- every image and cursor config needs to be changed. Hopefully will have it merged in soon &trade;

**Comment by keeferrourke** [comment]
Hey folks! New packages are available for download [here](https://www.pling.com/p/1148692/)! Let me know how they work out :)
