### ISSUE TITLE
Support for macOS

### ISSUE THREAD

**Issue by vasanthdeveloper** [keeferrourke/capitaine-cursors#36]
I have been using this cursor theme for a few years now. And I am still, in 😍 love with them! Recently I got my hands on macOS and very sadly 😢 the cursors aren't available for macOS. Is there any way I could build these cursors from the source for macOS?

Or, is releasing for macOS planned yet?

**Comment by keeferrourke** [comment]
I can take a look at what would be required!

**Comment by vasanthdeveloper** [comment]
Well, please do it. As these cursors are much more modern and professional than the macOS cursors.

**Comment by keeferrourke** [comment]
@vasanthdeveloper I appreciate the praise, but my full time job is elsewhere ;) I can't promise a timeline for this. At first glance, it doesn't look to be easy. macOS is a lot less customizable than other operating systems... :/

**Comment by vasanthdeveloper** [comment]
Oh, I will try to research if there is a theming system for macOS, or if the cursors are replaceable at all.

**Comment by keeferrourke** [comment]
This is looking... unlikely.

**Comment by keeferrourke** [comment]
It's possible to build the cursor set on macOS! If you run XQuartz applications, it may even be possible to use the cursor set as-is.

```
brew cask install inkscape xquartz
```

The built in macOS cursor files seem scattered about the operating system though, so I'm not sure how possible it will be to replace them.

**Comment by rocka** [comment]
Have a look at [alexzielenski/Mousecape](https://github.com/alexzielenski/Mousecape)? Since I'm not a macOS user, I don't know whether it works ...

**Comment by keeferrourke** [comment]
Here's a preliminary build for Mousecape! Tested and working on my mac, though some cursors seem to fall back to the default OS images on Mojave in some contexts. Better than nothing though? 🤷‍♂ 

[org.krourke.capitaine-cursors.cape.zip](https://github.com/keeferrourke/capitaine-cursors/files/4241835/org.krourke.capitaine-cursors.cape.zip)

**Comment by vasanthdeveloper** [comment]
It would be great if you could keep updating cape cursors for Mousecape for macOS and release an official version.
Now that I got Capitaine Cursors working on macOS Big Sur, I'm closing the issue. Good luck @keeferrourke 👍
