### ISSUE TITLE
Does this work on Unity + 16.04 Ubuntu ?

### ISSUE THREAD

**Issue by meetdilip** [keeferrourke/capitaine-cursors#5]
Is an X cursor theme different from what we use in Unity Desktop environment in Ubuntu 16.04 ? Can I make this work in 16.04 ? Thanks.

**Comment by keeferrourke** [comment]
Yes, an "xcursor" is simply the format used for cursors under X Windows, Wayland, Mir, and a lot of other display servers.

Compile and install this just like any other icon theme!

**Comment by meetdilip** [comment]
When I used ./build.sh inside **src** folder, I got 2 folders namely x1 and x2. How can use them in icon theme folder ? Put x1 and x2 into a folder and use it as icon theme ? Thanks.

**Comment by keeferrourke** [comment]
@meetdilip yes, running `./build,sh` will create folders called `src/x1/` and `src/x2`, however the compiled cursor theme is exported to `src/build/`.

if you are in the `src` folder, run
```
cp -pr build/ ~/.themes/capitaine-cursors
```
and then select the theme using any of your preferred desktop tools.
