### ISSUE TITLE
Could you please tell me how to custom the line weight?

### ISSUE THREAD

**Issue by AlynxZhou** [keeferrourke/capitaine-cursors#8]
Hello bro first I must thank you for your good work, I love this very much, but I find some small problems, I think the 工 shape and 十 shape cursor's line weight is too small, that is you are watching docs with light background and dark words, it's a little hard to find the cursor on the words, especially on a dark background with the 十 (+), can you tell me how to change this so I can try to find a proper size for myself (or other people)? I am also a cumputer-science student but I am freshman and known little about svg and cursor.
Thanks!

**Comment by AlynxZhou** [comment]
I think it may be better if we add a whith edge outside the crosshair like other icons. And the 工 shape need to get bolder a little.

**Comment by keeferrourke** [comment]
If I understand your question, simply edit these two files in Inkscape and then rerun the build script:
 * https://github.com/keeferrourke/capitaine-cursors/blob/master/src/svg/text.svg
 * https://github.com/keeferrourke/capitaine-cursors/blob/master/src/svg/crosshair.svg

```
./build.sh
```

**Comment by AlynxZhou** [comment]
Yes that's what I mean, you know that if we add white edges to the crosshair, it can be find easier, now it's hard to find it in a dark background :p

**Comment by AlynxZhou** [comment]
Sorry but I know a little about drawing, and I cannot draw it... I don't know how you draw it...

**Comment by keeferrourke** [comment]
Noted. I won't be updating this project until I have free time, of which I have none at the moment. If you want this issue solved quickly, I would suggest playing with it in inkscape. I'm not really willing to address this until the Fall.

**Comment by AlynxZhou** [comment]
Got it, I worry about that I don't know how you designed other icon and may add it in a wrong way so I cannot draw it…
