### ISSUE TITLE
AUR?

### ISSUE THREAD

**Issue by romanlex** [keeferrourke/capitaine-cursors#9]
Why your theme exist in AUR but icons not?

**Comment by keeferrourke** [comment]
I do not maintain AUR packages. There is an unofficial package (which just pull from git) for [La Capitaine](https://github.com/keeferrourke/la-capitaine-icon-theme) but I do not maintain it.

As far as I am concerned, packaging icons is pretty unnecessary, and I quite simply don't have the time to maintain distro-specific packages.

**Comment by keeferrourke** [comment]
If someone wants to make an AUR git package for this cursor theme, they are more than welcome.

**Comment by MggMuggins** [comment]
Whoever created the AUR package (for this repo, just the cursors), it no longer works. I hacked it so that it does:
```
# Maintainer: Daniel Lima <danielm@nanohub.tk>

pkgname=xcursor-capitaine
pkgver=r2.14.gfbb3887
pkgrel=1
pkgdesc='Capitaine Cursors - an x-cursor theme inspired by macOS and based on KDE Breeze'
arch=('any')
url='https://krourke.org/projects/art/capitaine-cursors'
license=('LGPLv3')
source=(git+https://github.com/keeferrourke/capitaine-cursors)
md5sums=('SKIP')

pkgver() {
	cd $srcdir/capitaine-cursors
	git describe --tags | sed 's/-/./g'
}

package() {
	cd $srcdir/capitaine-cursors
	install -d $pkgdir/usr/share/icons/
	cp -pr $srcdir/capitaine-cursors/dist/ $pkgdir/usr/share/icons/xcursor-capitaine
}
```

**Comment by keeferrourke** [comment]
@MggMuggins I recently simplified the organization of this project, so that makes sense. Would you be able to deliver your updated AUR package to the correct people? I do not maintain any official distribution repos or packages.

**Comment by MggMuggins** [comment]
I saw that you had done that. I ended up not bothering with the AUR anyway, just installing the cursors manually. I also don't have a lot of experience working with AUR recipes. Still, I'll contact the maintainer of this AUR package and see if he'll update it.

**Comment by keeferrourke** [comment]
We're in the official repositories now!
